---
# Region: us-east-1
# Template: path-to-template.yaml
# Parameters:
#   SomeInputParameter: some value
Tags:
  Owner: DevFactory
  Product: ses-custom-resources
  Severity: High
  Environment: production
  Contact: justin.menga@devfactory.com
  DeletionPolicy: Retain