---
Parameters:
  Prefix: ses-custom-resources
Tags:
  Owner: LearningTech
  Product: ses-custom-resources
  Severity: High
  Environment: sandbox
  Contact: justin.menga@learningtech.dev
  DeletionPolicy: Retain