---
# Region: us-east-1
# Template: path-to-template.yaml
# Parameters:
#   SomeInputParameter: some value
Tags:
  Owner: Learning Technology
  Product: ses-custom-resources
  Severity: High
  Environment: staging
  Contact: justin.menga@learning.com
  DeletionPolicy: Retain